[package]
name = "turbo_iot"
version = "2.2.8"
authors = ["Bowen Chiu <cbh@cameo.tw>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.104"
serde_derive = "1.0.104"
serde_json = "1.0"